<a href="https://colab.research.google.com/github/cabbi120101/TIL/blob/master/ML/%EC%9E%90%EC%8A%B5ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [ ]:
import numpy as np

#### Boolean indexing

In [ ]:
# 불린 인덱싱 (Boolean indexing)
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
test = np.arange(start = 10 , stop=100)
test30 = test[test<30]
print('시험 30보다 적은 수 :', test30)

시험 30보다 적은 수 : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [ ]:
array1d >5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


#### 선형대수 연산 -행렬 내적과 전치 행렬 구하기

In [ ]:
# 행렬 내적(행렬 곱)
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [ ]:
# 전치 행렬
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬 :\n', transpose_mat)

A의 전치행렬 :
 [[1 3]
 [2 4]]


## Pandas

DataFrame ix[]연산자

## 평가 성능평가 지표


In [1]:
import numpy as np
from sklearn.base import BaseEstimator

# 아무런 학습도 하지 않고 성별에 따라 생존자를 예측하는
# 단순한 Classifier 생성
# BaseEstimator 를 상속 받음
class MyDummyClassifier(BaseEstimator):
    # fit(): 아무것도 학습하지 않음
    def fit(self, X, y=None):
        pass

    # predict() : 단순히 Sex 피처가 1이면 0, 그렇지 않으면 1로 예측
    def predict(self, X):
        pred = np.zeros((X.shape[0],1)) # 예측값 초기화: 2차원 형태(, 1)
        for i in range(X.shape[0]):
            if X['Sex'].iloc[i] == 1 : # '남자'인 경우
                pred[i] = 0 # 사망
            else :
                pred[i] = 1

        return pred

In [3]:
# 타이타닉 데이터 전처리 함수(머신러닝05에서 쓴 데이터 전처리 함수)
from sklearn.preprocessing import LabelEncoder

# Null 처리 함수
def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    
    return df

# 머신러닝 알고리즘에 불필요한 속성 제거
def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    return df

# 레이블 인코딩 수행 함수
def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1] # 첫 문자만 추출
    
    features = ['Cabin', 'Sex', 'Embarked']
    
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    
    return df

# 위에서 만든 모든 함수를 한 번에 호출해서 사용하기 위한
# 함수 작성
def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    
    return df

In [4]:
# 타이타닉 생존자 예측

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 원본 데이터를 재로딩, 데이터 가공, 학습/테스트 데이터 세트로 분

titanic_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/멀티캠/머신러닝/titanic_train.csv')


# 결정값 (Label)
y_titanic_df = titanic_df['Survived']

X_titanic_df = titanic_df.drop('Survived', axis=1)

X_titanic_df = transform_features(X_titanic_df)

X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size=0.2, random_state=11)


# 위에서 생성한 MyDummyClassifier를 이용하여 학습/예측/평가 수행
my_clf = MyDummyClassifier()
my_clf.fit(X_train, y_train)

pred = my_clf.predict(X_test)

print('DummyClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))


DummyClassifier 정확도 : 0.8324
